app:
  test: testKey
  scheduler:
    interval: 10000
  database-access-type: JPA
  queue-name: "defaultQueue"
  exchange-name: "defaultExchange"
  routing-key: "defaultRoutingKey"
  use-queue: true


springdoc:
  swagger-ui:
    path: /swagger-ui.html

server:
  port: 8082

spring:
  jpa:
    properties:
      hibernate:
        generate_statistics: false
        format_sql: true
        show_sql: false
        jdbc:
          batch_size: 50
          fetch_size: 50
        order_inserts: true
        order_updates: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

  datasource:
    url: jdbc:postgresql://localhost:5433/scrapper
    username: ${SCRAPPER_POSTGRES_USER}
    password: ${SCRAPPER_POSTGRES_PASSWORD}
    driverClassName: org.postgresql.Driver

  liquibase:
    change-log: migrations/master.xml

management:
  server:
    port: 8084
  endpoints:
    enabled-by-default: true
    web:
      base-path: "/"
      exposure:
        include: [ "info", "health", "prometheus" ]
      path-mapping:
        prometheus: metrics
  endpoint:
    info.enabled: true
    health:
      enabled: true
      show-details: always
    prometheus.enabled: true
  prometheus.metrics.export.enabled: true
  metrics.tags:
      application: 'scrapper'

meta:
  rabbitmq:
    hostname: "localhost"
    user: ${SCRAPPER_RABBIT_MQ_USER}
    password: ${SCRAPPER_RABBIT_MQ_PASSWORD}
  updates:
   check-interval: "PT15S"
   github-events-per-page: 10
  bot:
    baseUrl: "http://localhost:8081"
