app:
  test: testKey
  token: ${TELEGRAM_BOT_API_TOKEN}
  scrapper-queue:
    queue-name: "defaultQueue"
    exchange-name: "defaultExchange"
    routing-key: "defaultRoutingKey"

springdoc:
  swagger-ui:
    path: /swagger-ui.html

server:
  port: 8081

management:
  server:
    port: 8083
  endpoints:
    enabled-by-default: true
    web:
      base-path: "/"
      exposure:
        include: [ "info", "health", "prometheus" ]
      path-mapping:
        prometheus: metrics
  endpoint:
    info.enabled: true
    health:
      enabled: true
      show-details: always
    prometheus.enabled: true
  prometheus.metrics.export.enabled: true
  metrics.tags:
    application: ${spring.application.name}

meta:
  rabbitmq:
    hostname: "localhost"
    user: ${SCRAPPER_RABBIT_MQ_USER}
    password: ${SCRAPPER_RABBIT_MQ_PASSWORD}
  paths:
    help-command-md: "./bot/src/main/resources/helpCommand.md"
  scrapper:
    baseUrl: "http://localhost:8082"


