app:
  test: testKey
  token: ${TELEGRAM_BOT_API_TOKEN}
  scrapper-queue:
    queue-name: "defaultQueue"
    exchange-name: "defaultExchange"
    routing-key: "defaultRoutingKey"

springdoc:
  swagger-ui:
    path: /swagger-ui.html

server:
  port: 8081

meta:
  paths:
    help-command-md: "./bot/src/main/resources/helpCommand.md"
  scrapper:
    baseUrl: "http://localhost:8082"


