app:
  test: testKey
  token: ${TELEGRAM_BOT_API_TOKEN}

springdoc:
  swagger-ui:
    path: /swagger-ui.html

server:
  port: 8081

meta:
  paths:
    help-command-md: "./bot/src/main/resources/helpCommand.md"
  scrapper:
    baseUrl: "http://localhost:8082"


