version: '3.8'
services:
 db:
  container_name: postgresql
  image: postgres:15
  restart: always
  environment:
   POSTGRES_USER: $POSTGRES_USER
   POSTGRES_PASSWORD: $POSTGRES_PASSWORD
   POSTGRES_DB: scrapper
  volumes:
   - "${POSTGRES_VOLUME}:/var/lib/postgresql/data"
  ports:
   - "${POSTGRES_OUT_PORT}:${POSTGRES_PORT}"
  networks:
   - backend
  healthcheck:
   test: [ "CMD-SHELL", "pg_isready -U postgres" ]
   interval: 10s
   timeout: 10s
   retries: 5

 liquibase-migrations:
  image: liquibase/liquibase:4.18
  restart: on-failure
  depends_on:
   db:
    condition: service_healthy
  command:
   --hub-mode=off
   --changelog-file=master.xml
   --driver=org.postgresql.Driver
   --url=jdbc:postgresql://postgresql:$POSTGRES_PORT/scrapper
   --username=$POSTGRES_USER
   --password=$POSTGRES_PASSWORD
   update
  volumes:
   - ./migrations:/liquibase/changelog
  networks:
   - backend

networks:
 backend:
  driver: bridge
