global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'bot-prometheus'
    metrics_path: '/metrics'
    scrape_interval: 5s
    static_configs:
      - targets: ['host.docker.internal:8083']

  - job_name: 'scrapper-prometheus'
    metrics_path: '/metrics'
    scrape_interval: 5s
    static_configs:
      - targets: [ 'host.docker.internal:8084' ]
