name: bot cicd flow

on:
  push:
    paths:
      - .github/workflows/bot.yml
      - SpringProject/bot/**
    branches: [ "main", "hw8"]
  pull_request:
    paths:
      - SpringProject/bot/**
    branches: [ "main" ]

permissions:
  packages: write

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: tinkoff-spring-bot
  IMAGE_VERSION: latest

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'oracle'
          cache: maven

      - name: List all files
        run: ls -la

      - name: Build with Maven
        run: |
         cd SpringProject/
         mvn package -pl bot -am

      - name: List SpringProject/bot
        run: ls SpringProject/bot

      - name: List SpringProject/bot/target
        run: ls SpringProject/bot/target/

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build bot image
        run: docker build -f SpringProject/bot/bot.Dockerfile -t ${{env.REGISTRY}}/${{github.actor}}/${{env.IMAGE_NAME}}:${{env.IMAGE_VERSION}} ./SpringProject/bot/

      - name: List docker images
        run: docker image ls

      - name: Push bot image
        run: docker push ${{env.REGISTRY}}/${{github.actor}}/${{env.IMAGE_NAME}}:${{env.IMAGE_VERSION}}

  checkstyle:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'oracle'
          cache: maven

      - name: Build with checkstyle
        run: |
         cd SpringProject/
         mvn -pl bot -am checkstyle:check