name: scrapper cicd flow

on:
  push:
    paths:
      - .github/workflows/scrapper.yml
      - SpringProject/scrapper/**
    branches: [ "main", "hw8"]
  pull_request:
    paths:
      - SpringProject/scrapper/**
    branches: [ "main" ]

permissions:
  packages: write

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: tinkoff-spring-scrapper
  IMAGE_VERSION: latest
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      SCRAPPER_RABBIT_MQ_USER: guest
      SCRAPPER_RABBIT_MQ_PASSWORD: guest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'oracle'
          cache: maven

      - name: List all files
        run: ls -la

      - name: Build with Maven
        run: |
         cd SpringProject/
         mvn package -pl scrapper -am

      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build scrapper image
        run: docker build -f SpringProject/scrapper/scrapper.Dockerfile -t ${{env.REGISTRY}}/${{github.actor}}/${{env.IMAGE_NAME}}:${{env.IMAGE_VERSION}} ./SpringProject/scrapper/

      - name: List docker images
        run: docker image ls

      - name: Push scrapper image
        run: docker push ${{env.REGISTRY}}/${{github.actor}}/${{env.IMAGE_NAME}}:${{env.IMAGE_VERSION}}

  checkstyle:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'oracle'
          cache: maven

      - name: Build with checkstyle
        run: |
         cd SpringProject/
         mvn -pl scrapper -am checkstyle:check